#!/usr/bin/env bash
set -e

# ==============================================================================
# Universal Cross-Platform Build & Release Pipeline for Diorama Sandbox
# Platforms: Linux (x86_64), Windows (x86_64), Android (ARM64)
# Features: Auto-versioning, Packaging, and GitHub Releases
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

export PATH="/opt/android-sdk/build-tools/37.0.0:/opt/android-sdk/platform-tools:$PATH"
export ANDROID_HOME="/opt/android-sdk"

DO_BUMP=false
DO_UPLOAD=false
TARGET_VERSION=""

# Parse CLI arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --bump)
            DO_BUMP=true
            shift
            ;;
        --no-bump)
            DO_BUMP=false
            shift
            ;;
        --upload|--release)
            DO_UPLOAD=true
            shift
            ;;
        --version)
            TARGET_VERSION="$2"
            shift 2
            ;;
        -v*)
            TARGET_VERSION="${1#v}"
            shift
            ;;
        *)
            if [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
                TARGET_VERSION="$1"
            else
                echo "Unbekannter Parameter: $1"
                echo "Aufruf: ./build_all.sh [--bump] [--no-bump] [--upload] [--version <x.y.z-beta.N>]"
                exit 1
            fi
            shift
            ;;
    esac
done

# Read current version
CURRENT_VERSION="0.1.0-beta.1"
if [ -f "VERSION" ]; then
    CURRENT_VERSION=$(cat VERSION | tr -d '[:space:]')
fi

# Determine new version
if [ -n "$TARGET_VERSION" ]; then
    VERSION="$TARGET_VERSION"
elif [ "$DO_BUMP" = true ]; then
    if [[ "$CURRENT_VERSION" =~ ^(.*-beta\.)([0-9]+)$ ]]; then
        PREFIX="${BASH_REMATCH[1]}"
        BUILD_NUM="${BASH_REMATCH[2]}"
        NEXT_BUILD_NUM=$((BUILD_NUM + 1))
        VERSION="${PREFIX}${NEXT_BUILD_NUM}"
    elif [[ "$CURRENT_VERSION" =~ ^([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
        VERSION="${BASH_REMATCH[1]}-beta.1"
    else
        VERSION="${CURRENT_VERSION}-beta.1"
    fi
else
    VERSION="$CURRENT_VERSION"
fi

# Determine Android version code (integer)
BUILD_CODE=1
if [[ "$VERSION" =~ beta\.([0-9]+) ]]; then
    BUILD_CODE="${BASH_REMATCH[1]}"
elif [[ "$VERSION" =~ \.([0-9]+)$ ]]; then
    BUILD_CODE="${BASH_REMATCH[1]}"
fi

echo "=========================================================="
echo "🏗️   Diorama Sandbox Build Pipeline"
echo "📌  Build Version : v${VERSION} (Code: ${BUILD_CODE})"
echo "🚀  Upload Release: ${DO_UPLOAD}"
echo "=========================================================="

# 1. Update VERSION file
echo "$VERSION" > VERSION

# 2. Update GDScript AppVersion
cat <<EOF > scripts/version.gd
# Auto-generated by build_all.sh. Do not edit manually.
class_name AppVersion

const VERSION: String = "$VERSION"
EOF

# 3. Update export_presets.cfg
if [ -f "export_presets.cfg" ]; then
    sed -i -E "s/version\/name=\".*\"/version\/name=\"$VERSION\"/g" export_presets.cfg
    sed -i -E "s/package\/version_name=\".*\"/package\/version_name=\"$VERSION\"/g" export_presets.cfg
    sed -i -E "s/package\/version_code=[0-9]+/package\/version_code=$BUILD_CODE/g" export_presets.cfg
    sed -i -E "s/version\/code=[0-9]+/version\/code=$BUILD_CODE/g" export_presets.cfg
    sed -i -E "s/application\/product_version=\".*\"/application\/product_version=\"$VERSION\"/g" export_presets.cfg
    sed -i -E "s/application\/file_version=\".*\"/application\/file_version=\"$VERSION\"/g" export_presets.cfg
fi

# Create directories
mkdir -p builds/linux builds/windows builds/android builds/dist

# ------------------------------------------------------------------------------
# Build 1: Linux x86_64
# ------------------------------------------------------------------------------
echo ""
echo "▶ [1/3] Building Linux (x86_64)..."
godot --headless --export-release "Linux / X11" builds/linux/DioramaSandbox.x86_64
chmod +x builds/linux/DioramaSandbox.x86_64
echo "✓ Linux Build Complete: builds/linux/DioramaSandbox.x86_64"

# ------------------------------------------------------------------------------
# Build 2: Windows Desktop x86_64
# ------------------------------------------------------------------------------
echo ""
echo "▶ [2/3] Building Windows Desktop (x86_64)..."
TEMPLATE_DIR="$HOME/.local/share/godot/export_templates/4.7.2.stable"
if [ -f "$TEMPLATE_DIR/windows_release_x86_64.exe" ]; then
    godot --headless --export-release "Windows Desktop" builds/windows/DioramaSandbox.exe
    echo "✓ Windows Executable Complete: builds/windows/DioramaSandbox.exe"
else
    echo "ℹ Windows release template not found in $TEMPLATE_DIR. Exporting PCK package..."
    godot --headless --export-pack "Windows Desktop" builds/windows/DioramaSandbox.pck
    echo "✓ Windows Data Package Complete: builds/windows/DioramaSandbox.pck"
fi

# ------------------------------------------------------------------------------
# Build 3: Android ARM64
# ------------------------------------------------------------------------------
echo ""
echo "▶ [3/3] Building Android (ARM64)..."
if [ -f "$TEMPLATE_DIR/android_debug.apk" ] || [ -f "$TEMPLATE_DIR/android_release.apk" ]; then
    godot --headless --export-debug "Android" builds/android/DioramaSandbox.apk
    echo "✓ Android APK Complete: builds/android/DioramaSandbox.apk"
else
    echo "ℹ Android export template not found. Exporting Android PCK package..."
    godot --headless --export-pack "Android" builds/android/DioramaSandbox.pck
    echo "✓ Android Data Package Complete: builds/android/DioramaSandbox.pck"
fi

# ------------------------------------------------------------------------------
# Packaging Release Archives
# ------------------------------------------------------------------------------
echo ""
echo "▶ Packaging Release Assets into builds/dist/..."
rm -f builds/dist/*

# Linux Archive
tar -czf "builds/dist/DioramaSandbox-v${VERSION}-linux-x86_64.tar.gz" -C builds/linux DioramaSandbox.x86_64 DioramaSandbox.pck
echo "  ✓ builds/dist/DioramaSandbox-v${VERSION}-linux-x86_64.tar.gz"

# Windows Archive
if [ -f "builds/windows/DioramaSandbox.exe" ]; then
    (cd builds/windows && zip -9 -q "../../builds/dist/DioramaSandbox-v${VERSION}-windows-x86_64.zip" DioramaSandbox.exe DioramaSandbox.pck)
    echo "  ✓ builds/dist/DioramaSandbox-v${VERSION}-windows-x86_64.zip"
fi

# Android APK
if [ -f "builds/android/DioramaSandbox.apk" ]; then
    cp builds/android/DioramaSandbox.apk "builds/dist/DioramaSandbox-v${VERSION}-android.apk"
    echo "  ✓ builds/dist/DioramaSandbox-v${VERSION}-android.apk"
fi

echo ""
echo "=========================================================="
echo "🎉 Build & Packaging Successful!"
echo "Version: v${VERSION}"
ls -lh builds/dist/
echo "=========================================================="

# ------------------------------------------------------------------------------
# Optional GitHub Release Upload
# ------------------------------------------------------------------------------
if [ "$DO_UPLOAD" = true ]; then
    echo ""
    echo "▶ Publishing Release to GitHub..."
    if ! command -v gh &> /dev/null; then
        echo "❌ 'gh' CLI tool not found. Cannot publish release."
        exit 1
    fi

    # Commit any version changes
    git add VERSION scripts/version.gd export_presets.cfg
    if ! git diff-index --quiet HEAD --; then
        git commit -m "chore(release): bump version to v${VERSION}"
    fi

    # Create local annotated tag
    git tag -a "v${VERSION}" -m "Release v${VERSION}" -f

    # Push to origin
    if git remote get-url origin &> /dev/null; then
        echo "▶ Pushing commits and tag to GitHub..."
        git push origin master --tags
    fi

    # Create GitHub Release
    echo "▶ Creating GitHub Release v${VERSION}..."
    gh release create "v${VERSION}" builds/dist/* \
        --title "Diorama Sandbox v${VERSION}" \
        --notes "### Diorama Sandbox v${VERSION}
- 🐧 **Linux (x86_64)**: \`DioramaSandbox-v${VERSION}-linux-x86_64.tar.gz\`
- 🪟 **Windows (x86_64)**: \`DioramaSandbox-v${VERSION}-windows-x86_64.zip\`
- 🤖 **Android (ARM64)**: \`DioramaSandbox-v${VERSION}-android.apk\`

*Automatisch erstellt über build_all.sh pipeline.*"

    echo "✓ GitHub Release v${VERSION} successfully published!"
fi
